grafana:
  adminPassword: "ganti-khusus-dev"
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts: 
      - grafana-dev.mawarpay.com
  persistence:
    enabled: true
    size: 5Gi

prometheus:
  prometheusSpec:
    retention: 7d
    storageSpec:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 20Gi
