grafana:
  adminPassword: "devadmin"
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts: 
      - grafana-dev.mawarpay.com
  persistence:
    enabled: true
    storageClassName: "gp3"
    size: 5Gi

prometheus:
  prometheusSpec:
    retention: 7d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: "gp3"
          resources:
            requests:
              storage: 20Gi