server:
  dev:
    enabled: false

  ha:
    enabled: false

  standalone:
    enabled: true
    config: |
      ui = true
      listener "tcp" {
        tls_disable = 1
        address     = "[::]:8200"
        cluster_address = "[::]:8201"
      }
      storage "raft" {
        path = "/vault/data"
      }

  dataStorage:
    enabled: true
    size: 10Gi
    storageClass: "gp3" 
    accessMode: ReadWriteOnce
    mountPath: "/vault/data"

  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - host: vault-dev.mawarpay.com
        paths: ["/"]

injector:
  enabled: true