server:
  dev:
    enabled: true

ui:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - host: vault-dev.mawarpay.com
        paths: 
          - /
