config:
  clients:
    - url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push

# agar Promtail dapat mengumpulkan log dari semua Node di EKS
tolerations:
  - operator: Exists
    effect: NoSchedule
  - operator: Exists
    effect: NoExecute